services:
  traefik:
    image: traefik:v3.4

    networks:
      - labs_proxy

    ports:
      - "80:80"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    command:
      - "--entrypoints.web.address=:80"

      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=labs_proxy"

      - "--api.dashboard=true"
      - "--api.insecure=false"

      - "--log.level=INFO"
      - "--accesslog=true"
      - "--metrics.prometheus=true"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${DASHBOARD_HOST}`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  whoami:
    image: traefik/whoami
    networks:
      - labs_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${WHOAMI_HOST}`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"

#  mongo:
#    image: mongo:latest
#    networks:
#      - labs_internal
#    env_file:
#      - ./mongo/.env.local
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
#    volumes:
#      - ./mongo/data:/data/db
#
#  auth-service:
#    build:
#      context: ./auth-service
#      dockerfile: Dockerfile
#    networks:
#      - labs_proxy
#      - labs_internal
#    env_file:
#      - ./auth-service/.env.local
#    command: [ "./app" ]
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.auth-service.rule=Host(`${AUTH_SERVICE_HOST}`)"
#      - "traefik.http.routers.auth-service.entrypoints=web"
#      - "traefik.http.services.auth-service.loadbalancer.server.port=3000"
#
#  gateway-service:
#    build:
#      context: ./gateway-service
#      dockerfile: Dockerfile
#    networks:
#      - labs_proxy
#      - labs_internal
#    env_file:
#      - ./gateway-service/.env.local
#    command: [ "./app" ]
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.gateway-service.rule=Host(`${GATEWAY_SERVICE_HOST}`)"
#      - "traefik.http.routers.gateway-service.entrypoints=web"
#      - "traefik.http.services.gateway-service.loadbalancer.server.port=3000"
#
#  web:
#    build:
#      context: ./web
#      dockerfile: Dockerfile
#    networks:
#      - labs_proxy
#    env_file:
#      - ./web/.env.local
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.web.rule=Host(`${WEB_HOST}`)"
#      - "traefik.http.routers.web.entrypoints=web"
#      - "traefik.http.services.web.loadbalancer.server.port=3000"

networks:
  labs_proxy:
    name: labs_proxy
    external: true
  labs_internal:
    name: labs_internal
    external: true