services:
  mongo:
    image: mongo:8.0.12
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  nats:
    image: nats:2.10.12-alpine
    restart: unless-stopped
    ports:
      - "8222:8222"
    command: ["-js", "-m", "8222"]
    volumes:
      - nats_data:/data

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./auth-service/.env
    command: [ "./app" ]

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./gateway-service/.env
    command: [ "./app" ]
    ports:
      - "3000:3000"

volumes:
  mongo_data:
  nats_data:
