name: Build and Push auth-service to Docker Hub

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Optional custom tag to push (e.g., v1.2.3)'
        required: false
        default: ''
  push:
    branches: [ main, master, develop ]
    paths:
      - 'auth-service/**'
      - 'auth-service-docker.yml'
    tags:
      - 'v*'

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/auth-service

jobs:
  docker:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute tags
        id: meta
        run: |
          REPO_IMAGE="${{ env.IMAGE_NAME }}"
          SHA_TAG="sha-${GITHUB_SHA::7}"

          TAGS=("${REPO_IMAGE}:${SHA_TAG}")

          # Branch-based tag
          if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            BRANCH="${GITHUB_REF#refs/heads/}"
            SAFE_BRANCH=${BRANCH//\//-}
            TAGS+=("${REPO_IMAGE}:${SAFE_BRANCH}")
            # latest only for main/master
            if [[ "$BRANCH" == "main" || "$BRANCH" == "master" ]]; then
              TAGS+=("${REPO_IMAGE}:latest")
            fi
          fi

          # Git tag (release)
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            GIT_TAG="${GITHUB_REF#refs/tags/}"
            TAGS+=("${REPO_IMAGE}:${GIT_TAG}")
          fi

          # Manual input tag
          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
            TAGS+=("${REPO_IMAGE}:${{ github.event.inputs.tag }}")
          fi

          # Output CSV
          TCSV=$(IFS=, ; echo "${TAGS[*]}")
          echo "tags=$TCSV" >> "$GITHUB_OUTPUT"

      - name: Build and push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./auth-service
          file: ./auth-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summary
        run: |
          echo "Pushed tags:" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n' >> $GITHUB_STEP_SUMMARY

# Notes:
# - Define repository secrets DOCKERHUB_USERNAME and DOCKERHUB_TOKEN (token or password with write perms).
# - Workflow triggers on pushes to auth-service/** in main/master/develop branches and on tags starting with v.
# - You can run manually and provide a custom tag via the workflow dispatch input.